language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.11"

before_install:
  - sudo rm -rf /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget gzip curl
