language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - sudo rm -rf /dev/shm
  - sudo ln -Tsf /{run,dev}/shm
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget gzip curl
