language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

sudo: false

before_install:
  - rm -rf /dev/shm
  - ln -Tsf /{run,dev}/shm
  - apt-get update -qq
  - apt-get install -qq wget gzip curl
